<?php

use Illuminate\Database\Seeder;
use App\Models\Merchant;

class MerchantsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [
            [
                'id' => 1,
                'user_id' => 1,
                'name' => '川东大院',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/1.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 66,
                'sales_count_month' => 686,
                'sales_total' => 999567,
                'click_total' => 8989
            ],
            [
                'id' => 2,
                'user_id' => 2,
                'name' => '味多美',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/2.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 56,
                'sales_count_month' => 678,
                'sales_total' => 67886,
                'click_total' => 88868
            ],
            [
                'id' => 3,
                'user_id' => 3,
                'name' => '上井',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/3.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 36,
                'sales_count_month' => 6768,
                'sales_total' => 657776,
                'click_total' => 6767
            ],
            [
                'id' => 4,
                'user_id' => 4,
                'name' => '汉泰',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/4.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 13,
                'sales_count_month' => 65,
                'sales_total' => 787,
                'click_total' => 8888
            ],
            [
                'id' => 5,
                'user_id' => 5,
                'name' => '溪雨观',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/5.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 18,
                'sales_count_month' => 59,
                'sales_total' => 56889,
                'click_total' => 566566
            ],
            [
                'id' => 6,
                'user_id' => 6,
                'name' => '澳门豆捞',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/6.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 29,
                'sales_count_month' => 567,
                'sales_total' => 56757,
                'click_total' => 5678
            ],
            [
                'id' => 7,
                'user_id' => 7,
                'name' => '鸿记煌',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/7.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 88,
                'sales_count_month' => 777,
                'sales_total' => 67868,
                'click_total' => 678
            ],
            [
                'id' => 8,
                'user_id' => 8,
                'name' => '小三不等位',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/8.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 34,
                'sales_count_month' => 678,
                'sales_total' => 567,
                'click_total' => 5677
            ],
            [
                'id' => 9,
                'user_id' => 9,
                'name' => '巴比伦溜冰场',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/9.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 88,
                'sales_count_month' => 888,
                'sales_total' => 8888,
                'click_total' => 8888
            ],
            [
                'id' => 10,
                'user_id' => 10,
                'name' => '老街',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/10.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 12,
                'sales_count_month' => 132,
                'sales_total' => 2311,
                'click_total' => 88818
            ],
            [
                'id' => 11,
                'user_id' => 11,
                'name' => '食锅拌拌',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/11.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 123,
                'sales_count_month' => 1231,
                'sales_total' => 12313,
                'click_total' => 121332
            ],
            [
                'id' => 12,
                'user_id' => 12,
                'name' => '海食上',
                'category_id' => 1,
                'category_name' => '美食',
                'mobile' => '021-123456,021-666666',
                'business_time' => '',
                'business_status' => 1,
                'logo' => 'https://www.zengyanqi.com/wp-content/uploads/2017/10/12.jpg',
                'banner' => '',
                'notice' => '欢迎光临',
                'province_id' => 9,
                'province' => '上海市',
                'city_id' => 106,
                'city' => '市辖区',
                'area_id' => 1139,
                'area' => '黄浦区',
                'address' => '半淞园路街道锦绣家园345号',
                'score' => 5,
                'average_time' => 35,
                'is_shelves' => 1,
                'fee' => 100,
                'min_delivery' => 2600,
                'collection_count' => 12,
                'sales_count' => 65,
                'sales_count_month' => 454,
                'sales_total' => 4533,
                'click_total' => 67877
            ],
        ];

        foreach ($list as $item) {
            $merchant = new Merchant();
            $merchant->id = $item['id'];
            $merchant->user_id = $item['user_id'];
            $merchant->name = $item['name'];
            $merchant->category_id = $item['category_id'];
            $merchant->category_name = $item['category_name'];
            $merchant->mobile = $item['mobile'];
            $merchant->business_time = $item['business_time'];
            $merchant->business_status = $item['business_status'];
            $merchant->logo = $item['logo'];
            $merchant->banner = $item['banner'];
            $merchant->notice = $item['notice'];
            $merchant->province_id = $item['province_id'];
            $merchant->province = $item['province'];
            $merchant->city_id = $item['city_id'];
            $merchant->city = $item['city'];
            $merchant->area_id = $item['area_id'];
            $merchant->area = $item['area'];
            $merchant->address = $item['address'];
            $merchant->score = $item['score'];
            $merchant->average_time = $item['average_time'];
            $merchant->is_shelves = $item['is_shelves'];
            $merchant->fee = $item['fee'];
            $merchant->min_delivery = $item['min_delivery'];
            $merchant->collection_count = $item['collection_count'];
            $merchant->sales_count = $item['sales_count'];
            $merchant->sales_count_month = $item['sales_count_month'];
            $merchant->sales_total = $item['sales_total'];
            $merchant->click_total = $item['click_total'];
            $merchant->save();
        }
    }

}
